# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0002_add_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopExternalId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_type', models.CharField(blank=True, help_text='Type of the external id', max_length=255)),
                ('external_id', models.CharField(blank=True, help_text='Value of the external id', max_length=255)),
                ('extra_data', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop')),
            ],
            options={
                'db_table': 'stop_external_id',
            },
        ),
    ]
