# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0003_stopexternalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimeLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('extra_data', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Trip')),
            ],
            options={
                'db_table': 'stop_time_limitation',
            },
        ),
    ]
